apiVersion: v1
kind: ConfigMap
metadata:
  name: photo-studio-config
data:
  PORT: "3000"
  MONGODB_URI: "mongodb://mongo-service:27017"
  MONGODB_AUTH_URI: "mongodb://mongo-service:27017/artgallery"
  MONGODB_FEEDBACK_URI: "mongodb://mongo-service:27017/artgallery"
  